![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

https://www.youtube.com/watch?v=mkbgEvUkSaM&list=PLv6MQO1ZzdmqKVL03HnslbBCDEoqS78Nm

# Intro to NumPy (Numerical Python)

NumPy is the fundamental package for scientific computing in Python. NumPy is used in many other packages in python even though you may not see it explicitly running in your code.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.




#### Import the numpy package using np as an alias

Remember: this line is required to use NumPy

In [1]:
import numpy as np

## Lists in Python

#### Create a list containing the values 1, 3, and 5

In [3]:
[1,3,5]

[1, 3, 5]

#### Create a list containing the values from 0 to 9 using the range function and assign it to L

In [22]:
L = list(range(0, 10)) # range(10) default start from 0
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Print the first element of list L

Remember: use [ ] notation to index a list

In [5]:
L[0]

0

## Arrays in Python

### Creating Arrays From Python Lists

#### Create an array containing the values [5, 4, 3, 2, 1] and store is in A

Remember: the np.array is used to create an array from a list

In [13]:
A = np.array(range(5, 0, -1))
A

array([5, 4, 3, 2, 1])

#### Print the datatype of array A

In [19]:
A.dtype

dtype('int64')

#### What is the expected datatype of this array? Why?

Enter the expected datatype between quotation marks

In [18]:
A2 = np.array([3.14, 4, 2, 3])
A2.dtype == 'float'

True

#### Create a multidimesional array from a multidimesional list 

Remember: multidimentional list = list containing lists

In [24]:
np.array([[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating Arrays from Scratch

#### NumPy has a variety of functions for efficiently creating arrays. In this section, use built-in NumPy functions to solve these problems


Remember: many NumPy functions take an arbitrary shape as input

Example: np.ones((2, 2)) creates a 2x2 array of ones

#### Create an integer array with 100 ones

In [33]:
np.ones(100) # but the default is float
np.ones(100, dtype='int') # int32, int64

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create a (4, 3) float array filled with zeros

In [26]:
np.zeros((4, 3)) # still float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Create a (5, 2) array filled with 6.28

In [36]:
np.full((5, 2), 5.28) # !!!!!!!!!!!!!!!!!!!!!!!!!!!!

array([[5.28, 5.28],
       [5.28, 5.28],
       [5.28, 5.28],
       [5.28, 5.28],
       [5.28, 5.28]])

#### Create an array filled with a linear sequence, started at 0, ending at 30, stepping by 3

Remember: for np.arange, the first parameter is inclusive, and the second parameter is exclusive, the expected array will contain 0 and not contain 30

In [39]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

#### Create an array of 9 evenly  spaced values between 0 and 64 inclusive

In [3]:
np.linspace(0, 64, 9) # linearly spaced

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

#### Create a (5, 2) array of uniformaly distributed random values between 0 and 1

In [4]:
np.random.random((5, 2))

array([[0.33991539, 0.27668462],
       [0.0075508 , 0.75886765],
       [0.38715215, 0.24385351],
       [0.05690089, 0.84978539],
       [0.49817448, 0.99785013]])

#### Create an array of 10 random integers in the interval [0, 5]

In [7]:
np.random.randint(0, 6, 10) # high is a 6, not 5

array([5, 3, 0, 0, 2, 5, 4, 5, 5, 0])

#### Create a (4, 4) identity matrix

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Understanding the built-in NumPy functions is crucial to understanding NumPy so practice using these functions on your own

## NumPy Standard Data Types

#### Understanding NumPy datatypes will give you an advantage in the furture so spend time looking at this table

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 