![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

https://www.youtube.com/watch?v=Yk3H3VRDfm0&list=PLv6MQO1ZzdmqKVL03HnslbBCDEoqS78Nm&index=3

https://www.youtube.com/watch?v=STJA-D-K9Cs&list=PLv6MQO1ZzdmqKVL03HnslbBCDEoqS78Nm&index=4

https://www.youtube.com/watch?v=0hjTJw9Jpmc&list=PLv6MQO1ZzdmqKVL03HnslbBCDEoqS78Nm&index=5

# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array.
We'll present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used in python.

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

#### Import the numpy package using np as an alias

In [24]:
import numpy as np

#### For the following questions x1, x2, and x3 refer to the arrays created below. Run this code to get started.

In [20]:
np.random.seed(1)  # seed for reproducibility

x1 = np.random.randint(10, size=9)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 3))  # Two-dimensional array
x3 = np.random.randint(10, size=(5, 4, 3))  # Three-dimensional array 

## NumPy Array Attributes

#### Print the ndim, shape, and size attributes of x2. The print code has already been created for you.

In [4]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)

x2 ndim:  2
x2 shape: (3, 3)
x2 size:  9


#### Print the dtype of x2

Remember: arrays have a single datatype for all elements

In [5]:
print("dtype:", x2.dtype)

dtype: int64


#### Print the itemsize and nbytes of x2

In [7]:
print("itemsize:", x2.itemsize, "bytes") # one int64 takes up 8 bytes
print("nbytes:",  x2.nbytes, "bytes") # 8 * 9 = 72

itemsize: 8 bytes
nbytes: 72 bytes


## Array Indexing: Accessing Single Elements

#### Print the first element of x1

In [9]:
x1

array([5, 8, 9, 5, 0, 0, 1, 7, 6])

In [8]:
x1[0]

5

#### Print the fifth element of x1

In [10]:
x1[4]

0

#### Print the second to last element of x1 using negative indicies

In [14]:
x1[-2]

7

### multi-dimensional array indexing 

#### Print the element at position (0,2) of x2

In [15]:
x2

array([[9, 2, 4],
       [5, 2, 4],
       [2, 4, 7]])

In [16]:
x2[0, 2]

4

#### Print the second element of the last row of x2 using positive and negative indicies 

In [17]:
x2[-1, 1]

4

#### Assign a value of 25 to the first element of the last row of x2

Remember: arrays have a fixed type, assigning a value of a different type will cause NumPy to implicitly change the type, this can lead to hard to find errors

In [18]:
x2[-1, 0] = 25
x2

array([[ 9,  2,  4],
       [ 5,  2,  4],
       [25,  4,  7]])

## Array Slicing: Accessing Subarrays

Remember: a slice of an array is not a clone, changing an element in an array slice will change that element in the original array and vice versa

### One-dimensional subarrays

In [21]:
x1

array([5, 8, 9, 5, 0, 0, 1, 7, 6])

#### Create a slice containing the last 5 elements of x1

In [22]:
x1[-5:]

array([0, 0, 1, 7, 6])

#### Create a slice containing every third element starting at the second element  of x1

In [26]:
x1[1::3]

array([8, 0, 7])

#### Create a slice where x1 has been reversed

In [25]:
x1[::-1]

array([6, 7, 1, 0, 0, 5, 9, 8, 5])

### Multi-dimensional subarrays


In [27]:
x2

array([[9, 2, 4],
       [5, 2, 4],
       [2, 4, 7]])

#### Create a slice containing the first two rows and first column of x2

In [32]:
x2[:2, :1]

array([[9],
       [5]])

#### Create a slice where the rows have been reversed for x2

In [33]:
x2[::-1, ::]

array([[2, 4, 7],
       [5, 2, 4],
       [9, 2, 4]])

#### Print the first column of x2

In [34]:
x2[:, 0]

array([9, 5, 2])

#### Print the first row of x2

In [35]:
x2[0, :]

array([9, 2, 4])

## Reshaping of Arrays



#### Create a range from 1 to 16 and reshape it into a (2, 8) array

Remember: the size of the original array must equal the size of the new array

In [45]:
x4 = np.arange(1, 17)
x4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [42]:
x4.reshape((2, 8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

#### Reshape x1 into a 1 dimensional column using slice notation and np.newaxis

In [48]:
x1[:, np.newaxis]

array([[5],
       [8],
       [9],
       [5],
       [0],
       [0],
       [1],
       [7],
       [6]])

In [52]:
x1.shape, x1[:, np.newaxis].shape, x1[np.newaxis, :].shape

((9,), (9, 1), (1, 9))

## Array Concatenation and Splitting

### Concatenation of arrays


#### Concatenate arrays x and y

In [56]:
x = np.array([2, 4, 6])
y = np.array([8, 10, 12])

np.concatenate([x, y])

array([ 2,  4,  6,  8, 10, 12])

#### Concatenate arrays x, y, and z

In [57]:
z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 2,  4,  6,  8, 10, 12, 99, 99, 99])

#### Concatenate grid with itself along the second axis

In [60]:
grid = np.array([[5, 4, 1],
                 [4, 5, 6]])

# np.concatenate([grid, grid])
np.concatenate([grid, grid], axis=1)

array([[5, 4, 1, 5, 4, 1],
       [4, 5, 6, 4, 5, 6]])

#### Concatenate x and grid using the vstack function

Why can't x and grid be concatenated using the hstack function?

In [64]:
print(x)
print(grid)

np.vstack([x, grid]) # vertically stack

[2 4 6]
[[5 4 1]
 [4 5 6]]


array([[2, 4, 6],
       [5, 4, 1],
       [4, 5, 6]])

### Splitting of arrays

#### Split x on element 4 and element 7

In [67]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

x1, x2, x3 = np.split(x, [3, 6])
x1, x2, x3

(array([1, 2, 3]), array([99, 99,  3]), array([2, 1]))

#### Split grid on row 2

In [68]:
grid = np.arange(25).reshape((5, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Split grid on column 3

In [75]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]
 [20 21 22]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
