In [1]:
import numpy as np

In [2]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [6]:
x[[3, 7, 4]]

array([71, 86, 60])

In [4]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [7]:
X = np.arange(12).reshape((3, 4))
print(X)
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 2,  5, 11])

In [9]:
print(row[:, np.newaxis])
X[row[:, np.newaxis], col] # broadcasting

[[0]
 [1]
 [2]]


array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])