In [1]:
import numpy as np
np.__version__

'1.16.2'

In [2]:
np?

Type:        module
String form: <module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippet

# darray

dtypes: float, int, bool, datetime64\[ns\], timedelta\[ns\], and object

dtypes have item sizes, e.g. int64 and int32

In [7]:
a = np.array([1,2,3,4])
b = np.array([1.1, 2, 3, 4])
a, b, type(a), type(b), type(a[0]), type(b[1])
#                         int         float

(array([1, 2, 3, 4]),
 array([1.1, 2. , 3. , 4. ]),
 numpy.ndarray,
 numpy.ndarray,
 numpy.int64,
 numpy.float64)

In [9]:
c = np.array([1,2,3,4], dtype='float32')
# c = np.array([1,2,3,4], dtype=np.float32)
c, type(c[0])

(array([1., 2., 3., 4.], dtype=float32), numpy.float32)

# basic arrays

In [10]:
z = np.zeros(10, dtype=int)
o = np.ones((3, 5), dtype=float)
z, o

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [11]:
f = np.full((3, 5), 3.14)
f

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
np.random.random((3, 3))

array([[0.45709821, 0.36458367, 0.41326026],
       [0.12106747, 0.96124239, 0.44161893],
       [0.32296075, 0.04176074, 0.34591715]])

In [16]:
# Create a 3x3 array of normally distributed random values 
# # with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3, 4))
#             mean std  shape

array([[-0.75705123,  0.03625322, -0.03127632, -0.50217868],
       [-0.72343422,  0.52411175, -0.21639777, -1.06587333],
       [ 0.96705563,  1.93874953,  2.50716833, -0.8904652 ]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10) 
np.random.randint(0, 10, (2, 3))

array([[4, 3, 1],
       [4, 0, 7]])

In [19]:
# Create a 3x3 identity matrix 
np.eye(3) # I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that # memory location
np.empty(3)

array([1., 1., 1.])