# Setup

In [2]:
import numpy as np
np.__version__

'1.16.2'

# darray

dtypes: float, int, bool, datetime64\[ns\], timedelta\[ns\], and object

dtypes have item sizes, e.g. int64 and int32

In [7]:
a = np.array([1,2,3,4])
b = np.array([1.1, 2, 3, 4])
a, b, type(a), type(b), type(a[0]), type(b[1])
#                         int         float

(array([1, 2, 3, 4]),
 array([1.1, 2. , 3. , 4. ]),
 numpy.ndarray,
 numpy.ndarray,
 numpy.int64,
 numpy.float64)

In [9]:
c = np.array([1,2,3,4], dtype='float32')
# c = np.array([1,2,3,4], dtype=np.float32)
c, type(c[0])

(array([1., 2., 3., 4.], dtype=float32), numpy.float32)

# basic arrays

In [10]:
z = np.zeros(10, dtype=int)
o = np.ones((3, 5), dtype=float)
z, o

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [11]:
f = np.full((3, 5), 3.14)
f

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
np.random.random((3, 3))

array([[0.45709821, 0.36458367, 0.41326026],
       [0.12106747, 0.96124239, 0.44161893],
       [0.32296075, 0.04176074, 0.34591715]])

In [16]:
# Create a 3x3 array of normally distributed random values 
# # with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3, 4))
#             mean std  shape

array([[-0.75705123,  0.03625322, -0.03127632, -0.50217868],
       [-0.72343422,  0.52411175, -0.21639777, -1.06587333],
       [ 0.96705563,  1.93874953,  2.50716833, -0.8904652 ]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10) 
np.random.randint(0, 10, (2, 3))

array([[4, 3, 1],
       [4, 0, 7]])

In [19]:
# Create a 3x3 identity matrix 
np.eye(3) # I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that # memory location
np.empty(3)

array([1., 1., 1.])

# Array Attributes

In [4]:
np.random.seed(0) # seed for reproducibility
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

print("x3 ndim: ", x3.ndim) # the number of dimensions
print("x3 shape:", x3.shape) # the size of each dimension
print("x3 size: ", x3.size) # the total size of the array
print("dtype:", x3.dtype) # only one type for the entire array
print("itemsize:", x3.itemsize, "bytes") # the size (in bytes) of each array element
print("nbytes:", x3.nbytes, "bytes") # total size (in bytes) of the array

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


# Array Indexing & slicing

In [6]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x1, x2

(array([5, 0, 3, 3, 7, 9]),
 array([[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]]))

In [9]:
print(x1[0], x1[-2])
print(x2[0, 0], x2[2, 1])

5 7
3 6


In [10]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [11]:
### must be the same dtype, or will be truncated
x1[0] = 3.14
x1

array([3, 0, 3, 3, 7, 9])

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[:5], x[4:7]

(array([0, 1, 2, 3, 4]), array([4, 5, 6]))

In [14]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [15]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [16]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
x[5::-2] # reversed every other from index 5
# this one is strange

array([5, 3, 1])

In [19]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [20]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [21]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [22]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

## Single Row/Column

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [23]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [25]:
print(x2[0, :]) # first row of x2

[12  5  2  4]


**array slices return views rather than copies of the array data.** This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

### Copy of slices

In [27]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[12,  5],
       [ 7,  6]])

# Reshaping of Arrays

In [28]:
grid = np.arange(1, 10).reshape((3, 3)) 
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
x = np.array([1, 2, 3, 4, 5, 6]) # row vector via reshape
y = x.reshape((2, 3))
x, y

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [32]:
# row matrix
x = np.array([1, 2, 3]) # row vector via reshape
y = x.reshape((1, 3))
z = x[np.newaxis, :]
y, z

(array([[1, 2, 3]]), array([[1, 2, 3]]))

In [33]:
# column matrix
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [34]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting