In [33]:
import torch
import numpy as np

In [7]:
x = torch.empty(3)
print(x)
x = torch.empty(2, 3)
print(x)
x = torch.empty(2, 3, 4)
print(x)
x = torch.empty(2, 2, 3, 4)
print(x)

tensor([9.1477e-41, 0.0000e+00, 4.2039e-45])
tensor([[ 0.0000e+00, -2.5244e-29, -9.2336e-02],
        [-2.5250e-29,  1.1210e-44,  0.0000e+00]])
tensor([[[ 2.0000e+00,  1.4347e+00,  8.4078e-45,  3.6734e-40],
         [ 7.5848e-30,  1.4013e-45,  0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  7.3929e-30,  1.4013e-45],
         [ 9.1477e-41, -2.5244e-29,  1.1210e-44,  0.0000e+00],
         [ 1.4013e-45, -2.5244e-29,  7.6008e-30,  1.4013e-45]]])
tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00, -2.5244e-29,  0.0000e+00, -2.5244e-29],
          [ 5.6052e-

In [9]:
x = torch.rand(2, 3)
print(x)
x = torch.zeros(2, 3)
print(x)
x = torch.ones(2, 3)
print(x)

tensor([[0.3066, 0.8591, 0.1843],
        [0.4854, 0.1499, 0.0887]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x = torch.ones(2, 3, dtype=torch.int)
print(x.dtype)
x = torch.ones(2, 3, dtype=torch.double)
print(x.dtype)
x = torch.ones(2, 3, dtype=torch.float16)
print(x.dtype)

torch.int32
torch.float64
torch.float16


In [15]:
x = torch.ones(2, 3)
print(x.size())
print(x.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [16]:
x = torch.tensor([2.5, 6.9])
x

tensor([2.5000, 6.9000])

In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
# element wise operation
z = x + y
print(z)
z = torch.add(x, y)
print(z)
# in-place operation
y.add_(x) ### anything with _ is in-place
print(y)

tensor([[0.2840, 1.3006],
        [1.6794, 1.9393]])
tensor([[0.2840, 1.3006],
        [1.6794, 1.9393]])
tensor([[0.2840, 1.3006],
        [1.6794, 1.9393]])


In [22]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
# element wise operation
z = x - y
print(z)
z = torch.sub(x, y)
print(z)
# in-place operation
x.sub_(y) ### anything with _ is in-place
print(x)

tensor([[-0.0688, -0.0933],
        [ 0.3334,  0.4275]])
tensor([[-0.0688, -0.0933],
        [ 0.3334,  0.4275]])
tensor([[-0.0688, -0.0933],
        [ 0.3334,  0.4275]])


In [23]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
# element wise operation
z = x * y
print(z)
z = torch.mul(x, y)
print(z)
# in-place operation
y.mul_(x) ### anything with _ is in-place
print(y)

tensor([[0.8074, 0.0928],
        [0.1997, 0.2392]])
tensor([[0.8074, 0.0928],
        [0.1997, 0.2392]])
tensor([[0.8074, 0.0928],
        [0.1997, 0.2392]])


In [27]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
# element wise operation
z = x / y
print(z)
z = torch.div(x, y)
print(z)
# in-place operation
x.div_(y) ### anything with _ is in-place
print(x)

tensor([[1.6641, 0.4048],
        [2.2084, 1.2837]])
tensor([[1.6641, 0.4048],
        [2.2084, 1.2837]])
tensor([[1.6641, 0.4048],
        [2.2084, 1.2837]])


In [30]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) # column
print(x[1, :]) # row
print(x[1, 1]) # element
print(x[1, 1].item()) # get element value; item() is only for one element

tensor([[0.9083, 0.5013, 0.0297],
        [0.2458, 0.6937, 0.2411],
        [0.7888, 0.5521, 0.8835],
        [0.0582, 0.1608, 0.6599],
        [0.0756, 0.5395, 0.2408]])
tensor([0.9083, 0.2458, 0.7888, 0.0582, 0.0756])
tensor([0.2458, 0.6937, 0.2411])
tensor(0.6937)
0.6936569809913635


In [32]:
x = torch.rand(4, 4)
y = x.view(16)
print(y)
y = x.view(-1, 8)
print(y)

tensor([0.6202, 0.7341, 0.8362, 0.6971, 0.1937, 0.1623, 0.7280, 0.0409, 0.5771,
        0.1953, 0.8092, 0.4588, 0.3513, 0.9328, 0.6795, 0.7336])
tensor([[0.6202, 0.7341, 0.8362, 0.6971, 0.1937, 0.1623, 0.7280, 0.0409],
        [0.5771, 0.1953, 0.8092, 0.4588, 0.3513, 0.9328, 0.6795, 0.7336]])


In [37]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b, type(b))
### careful!!!!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [38]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
### careful again!!
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [40]:
print(torch.cuda.is_available()) # here is False
if torch.cuda.is_available():
    device = torch.device('cuda') 
    x = torch.ones(5, device=device) # on GPU
    y = torch.ones(5) # on CPU
    y = y.to(device) # to GPU
    z = x + y # operate on GPU
    z = z.to('cuda') # back to CPU

False
